# Project: vortex-listener vortex-client

CC       = gcc.exe
OBJ      = vortex-listener.o \
           vortex-client.o
PROGRAMS = vortex-listener.exe \
	   vortex-client.exe

BASE_DIR = C:/libraries
LIBS     = -Wall -g \
	-L"$(BASE_DIR)/lib" \
	-L"$(BASE_DIR)/lib/glib-2.0" \
	-L"../src" \
	-lglib-2.0 -lgmodule-2.0 -lgthread-2.0 -liconv -lintl \
	-lvortex-1.0 \
	-lreadline

INCS =  \
	-I"$(BASE_DIR)/include" \
	-I"$(BASE_DIR)/include/glib-2.0" \
        -I"$(BASE_DIR)/include/libxml2" \
        -I"$(BASE_DIR)/lib/glib-2.0/include" -I"../src" 

CFLAGS   = $(INCS) -DVERSION=\""$(VORTEX_VERSION)"\" -Wall -g

.PHONY: all all-before all-after clean clean-custom

all: all-before $(PROGRAMS) all-after links

all-before:
	cd ../src;make -f Makefile.win

clean: clean-custom
	${RM} $(OBJ) $(PROGRAMS) *.dll

vortex-listener.exe: vortex-listener.o
	$(CC) -mconsole $< -o $@ $(LIBS)

vortex-client.exe: vortex-client.o
	$(CC) -mconsole $< -o $@ $(LIBS)

links:

	cp ../src/libvortex-1.0.dll .
	cp ../data/channel.dtd .

%.o: %.c
	$(CC) -c $< -o $@ $(CFLAGS)
